"""Canonical Unicode and ASCII animation catalog."""

from __future__ import annotations

from typing import Literal

from .braille import Spinner
from .braille import spinners as _braille_spinners

CategoryName = Literal[
    "subtle",
    "scan",
    "build",
    "thinking",
    "tool",
    "data",
    "graph",
    "progress",
    "alert",
    "dense",
]

SpinnerName = Literal[
    "braille",
    "braillewave",
    "dna",
    "scan",
    "rain",
    "scanline",
    "pulse",
    "snake",
    "sparkle",
    "cascade",
    "columns",
    "orbit",
    "breathe",
    "waverows",
    "checkerboard",
    "helix",
    "fillsweep",
    "diagswipe",
    "softdot",
    "slowbreath",
    "quietorbit",
    "dimwave",
    "hscan",
    "vscan",
    "radar",
    "focusbeam",
    "blocks",
    "stack",
    "assemble",
    "brickline",
    "ellipsis",
    "mindwave",
    "synapse",
    "neuron",
    "terminalblink",
    "gearspin",
    "wrench",
    "sparkplug",
    "bitstream",
    "packetflow",
    "matrixrain",
    "columns2",
    "nodes",
    "edgepulse",
    "cluster",
    "orbitnodes",
    "meter",
    "ladder",
    "risingblocks",
    "fillbar2",
    "warningpulse",
    "heartbeat",
    "ping",
    "flashdot",
    "plasma",
    "noise",
    "moire",
    "shimmergrid",
]

CATEGORY_NAMES: tuple[CategoryName, ...] = (
    "subtle",
    "scan",
    "build",
    "thinking",
    "tool",
    "data",
    "graph",
    "progress",
    "alert",
    "dense",
)

SPINNER_NAMES: tuple[SpinnerName, ...] = (
    "braille",
    "braillewave",
    "dna",
    "scan",
    "rain",
    "scanline",
    "pulse",
    "snake",
    "sparkle",
    "cascade",
    "columns",
    "orbit",
    "breathe",
    "waverows",
    "checkerboard",
    "helix",
    "fillsweep",
    "diagswipe",
    "softdot",
    "slowbreath",
    "quietorbit",
    "dimwave",
    "hscan",
    "vscan",
    "radar",
    "focusbeam",
    "blocks",
    "stack",
    "assemble",
    "brickline",
    "ellipsis",
    "mindwave",
    "synapse",
    "neuron",
    "terminalblink",
    "gearspin",
    "wrench",
    "sparkplug",
    "bitstream",
    "packetflow",
    "matrixrain",
    "columns2",
    "nodes",
    "edgepulse",
    "cluster",
    "orbitnodes",
    "meter",
    "ladder",
    "risingblocks",
    "fillbar2",
    "warningpulse",
    "heartbeat",
    "ping",
    "flashdot",
    "plasma",
    "noise",
    "moire",
    "shimmergrid",
)

_ASCII_SPINNERS: dict[SpinnerName, Spinner] = {
    "softdot": Spinner(frames=(".", "o", "O", "o"), interval=140),
    "slowbreath": Spinner(frames=(".", "-", "=", "#", "=", "-"), interval=160),
    "quietorbit": Spinner(frames=(".", ":", "*", ":"), interval=140),
    "dimwave": Spinner(frames=("-", "~", "=", "~"), interval=150),
    "hscan": Spinner(frames=(">---", "->--", "-->-", "--->"), interval=90),
    "vscan": Spinner(frames=("|", "/", "-", "\\"), interval=100),
    "radar": Spinner(frames=(".   ", "..  ", "... ", "....", "... ", "..  "), interval=120),
    "focusbeam": Spinner(frames=("----", "===-", "-===", "--==", "---="), interval=90),
    "blocks": Spinner(frames=("[   ]", "[=  ]", "[== ]", "[===]", "[ ==]", "[  =]"), interval=110),
    "stack": Spinner(frames=("_  ", "=  ", "#  ", "## ", "###"), interval=140),
    "assemble": Spinner(frames=(". . .", ":. .:", "::.::", ":::::", ".:::."), interval=120),
    "brickline": Spinner(frames=("[]  ", "[][]", " [] ", "  []"), interval=130),
    "ellipsis": Spinner(frames=(".  ", ".. ", "...", ".. "), interval=180),
    "mindwave": Spinner(frames=("~  ", "~~ ", "~~~", "~~ "), interval=140),
    "synapse": Spinner(frames=("*..", ".*.", "..*", ".*."), interval=100),
    "neuron": Spinner(frames=("o..", ".o.", "..o", ".o."), interval=110),
    "terminalblink": Spinner(frames=("$_", "$ "), interval=160),
    "gearspin": Spinner(frames=("|", "/", "-", "\\"), interval=90),
    "wrench": Spinner(frames=("-T-", "-|-", "-T-", "-|-"), interval=120),
    "sparkplug": Spinner(frames=("*--", "-*-", "--*", "-*-"), interval=100),
    "bitstream": Spinner(frames=("1000", "0100", "0010", "0001"), interval=90),
    "packetflow": Spinner(frames=("[>]---", "-[>]--", "--[>]-", "---[>]"), interval=100),
    "matrixrain": Spinner(frames=("|..", ".|.", "..|", ".|."), interval=100),
    "columns2": Spinner(frames=("| |", " ||", "|| ", " | "), interval=110),
    "nodes": Spinner(frames=("o--o", "o==o", "O==o", "o==O"), interval=110),
    "edgepulse": Spinner(frames=("o---o", "o=--o", "o-=-o", "o--=o"), interval=90),
    "cluster": Spinner(frames=(".o.", "oOo", ".O.", "oOo"), interval=120),
    "orbitnodes": Spinner(frames=("o.o", ".o.", "o.o", "O.o"), interval=120),
    "meter": Spinner(frames=("[   ]", "[=  ]", "[== ]", "[===]"), interval=120),
    "ladder": Spinner(frames=("_", "=", "#", "=", "_"), interval=140),
    "risingblocks": Spinner(frames=("_", "-", "=", "#", "="), interval=120),
    "fillbar2": Spinner(frames=("....", "=...", "==..", "===.", "===="), interval=100),
    "warningpulse": Spinner(frames=("!  ", " ! ", "  !", " ! "), interval=140),
    "heartbeat": Spinner(frames=("_/_", "_/\\", "_/_", "___"), interval=140),
    "ping": Spinner(frames=(".  ", "o  ", "O  ", "o  "), interval=130),
    "flashdot": Spinner(frames=("*", ".", "*", " "), interval=160),
    "plasma": Spinner(frames=("~*~", "*~*", "~#~", "*~*"), interval=80),
    "noise": Spinner(frames=(".:*", "*:.", ":*.", ".*:"), interval=90),
    "moire": Spinner(frames=("///", "---", "|||", "---"), interval=100),
    "shimmergrid": Spinner(frames=(".+.", "+.+", "*+*", "+.+"), interval=90),
}

spinners: dict[SpinnerName, Spinner] = {**_braille_spinners, **_ASCII_SPINNERS}

SPINNER_CATEGORIES: dict[SpinnerName, CategoryName] = {
    "braille": "subtle",
    "braillewave": "data",
    "dna": "data",
    "scan": "scan",
    "rain": "data",
    "scanline": "scan",
    "pulse": "subtle",
    "snake": "scan",
    "sparkle": "alert",
    "cascade": "data",
    "columns": "data",
    "orbit": "subtle",
    "breathe": "subtle",
    "waverows": "data",
    "checkerboard": "dense",
    "helix": "data",
    "fillsweep": "progress",
    "diagswipe": "scan",
    "softdot": "subtle",
    "slowbreath": "subtle",
    "quietorbit": "subtle",
    "dimwave": "subtle",
    "hscan": "scan",
    "vscan": "scan",
    "radar": "scan",
    "focusbeam": "scan",
    "blocks": "build",
    "stack": "build",
    "assemble": "build",
    "brickline": "build",
    "ellipsis": "thinking",
    "mindwave": "thinking",
    "synapse": "thinking",
    "neuron": "thinking",
    "terminalblink": "tool",
    "gearspin": "tool",
    "wrench": "tool",
    "sparkplug": "tool",
    "bitstream": "data",
    "packetflow": "data",
    "matrixrain": "data",
    "columns2": "data",
    "nodes": "graph",
    "edgepulse": "graph",
    "cluster": "graph",
    "orbitnodes": "graph",
    "meter": "progress",
    "ladder": "progress",
    "risingblocks": "progress",
    "fillbar2": "progress",
    "warningpulse": "alert",
    "heartbeat": "alert",
    "ping": "alert",
    "flashdot": "alert",
    "plasma": "dense",
    "noise": "dense",
    "moire": "dense",
    "shimmergrid": "dense",
}


def spinner_names_for_category(category: str) -> tuple[SpinnerName, ...]:
    if category not in CATEGORY_NAMES:
        raise KeyError(category)
    return tuple(name for name in SPINNER_NAMES if SPINNER_CATEGORIES[name] == category)


BrailleSpinnerName = SpinnerName
BRAILLE_SPINNER_NAMES = SPINNER_NAMES

__all__ = [
    "BRAILLE_SPINNER_NAMES",
    "CATEGORY_NAMES",
    "SPINNER_CATEGORIES",
    "SPINNER_NAMES",
    "BrailleSpinnerName",
    "CategoryName",
    "SpinnerName",
    "spinner_names_for_category",
    "spinners",
]
